---@meta _

--- AUTO-GENERATED BY stubgen.ts — DO NOT EDIT MANUALLY.
--- EdgeTX Lua API stubs for lua-language-server (LuaLS)
--- model.* model configuration functions

---@class (exact) modelLib
model = {}

